[Ruby]
if=if %cursor%\n\t%cursor%\nend\n%cursor%
el=else\n\t
wh=while %cursor%\n\t%cursor%\nend\n%cursor%
fo=for %cursor%\n\t%cursor%\nend\n%cursor%
de=def %cursor%\n\t%cursor%\nend\n%cursor%
dc=def self.%cursor%\n\t%cursor%\nend\n%cursor%
mo=module %cursor%\n\t%cursor%\nend
cl=class %cursor%\n\t%cursor%\nend
in=def initialize(%cursor%)\n\t%cursor%\nend\n\n%cursor%
pu=puts %cursor%
ut=#encoding:utf-8\n%cursor%
re=require_relative '%cursor%'